name: Test Refresh Script

on:
  schedule:
    - cron: "0,10,20 * * * *"   
  workflow_dispatch:            

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: List files
        run: ls -R

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Debug secrets
        run: |
          echo "MONGO_URI starts with: ${MONGO_URI:0:20}"
          echo "SPOTIFY_CLIENT_ID starts with: ${SPOTIFY_CLIENT_ID:0:5}"
          echo "SPOTIFY_CLIENT_SECRET starts with: ${SPOTIFY_CLIENT_SECRET:0:5}"
          echo "RAPIDAPI_KEYS starts with: ${RAPIDAPI_KEYS:0:5}"
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          RAPIDAPI_KEYS: ${{ secrets.RAPIDAPI_KEYS }}

      - name: Run saveToMongo.js
        run: node scripts/saveToMongo.js
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          RAPIDAPI_KEYS: ${{ secrets.RAPIDAPI_KEYS }}


